# Generated by Django 3.2.11 on 2022-03-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220205_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.CharField(blank=True, default='default.png', max_length=36, null=True),
        ),
    ]
