# Generated by Django 3.2.11 on 2022-03-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220320_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.CharField(blank=True, default='3.0', max_length=10, null=True),
        ),
    ]
