version: "3.9"

services:
  db:
    image: postgres:11
    volumes:
      - ~/data/db:/var/lib/postgresql/data
    environment:
      - PRODUCTION=false
    env_file:
      - ./config/.env.dev
    ports:
      - "5435:5432"
  web:
    build: .
    command: >
        sh -c "/wait-for-it.sh db:5432 -- python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - ./wait-for-it.sh:/wait-for-it.sh
    environment:
      - PRODUCTION=false
    env_file:
      - ./config/.env.dev
    ports:
      - "8000:8000"
    depends_on:
      - db