# Generated by Django 3.2.7 on 2021-10-08 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tennis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='leagueplayer', to=settings.AUTH_USER_MODEL),
        ),
    ]
