# Generated by Django 4.0.1 on 2022-01-31 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0002_matchrequest_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=2000, null=True),
        ),
    ]
