# Generated by Django 3.2.8 on 2021-10-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0002_alter_match_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
