# Generated by Django 3.2.8 on 2021-10-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0003_alter_league_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='state',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
