# Generated by Django 3.2.8 on 2021-10-15 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tennis', '0004_auto_20211014_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='players',
        ),
        migrations.CreateModel(
            name='LeagueApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=64)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league', to='tennis.league')),
                ('players', models.ManyToManyField(blank=True, related_name='leagueplayer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
