# Generated by Django 3.2.11 on 2022-02-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0005_matchrequest_requested_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='Ongoing', max_length=64),
        ),
    ]
