# Generated by Django 3.2.8 on 2021-10-15 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tennis', '0005_auto_20211015_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leagueapplication',
            name='players',
        ),
        migrations.AddField(
            model_name='leagueapplication',
            name='players',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leagueplayer', to=settings.AUTH_USER_MODEL),
        ),
    ]
