# Generated by Django 3.2.11 on 2022-03-10 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tennis', '0006_league_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='winner_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='league_wone', to=settings.AUTH_USER_MODEL, to_field='user_id'),
        ),
        migrations.AddField(
            model_name='league',
            name='winner_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='league_wtwo', to=settings.AUTH_USER_MODEL, to_field='user_id'),
        ),
        migrations.AlterField(
            model_name='league',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=64),
        ),
    ]
