# Generated by Django 4.0.1 on 2022-01-18 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tennis.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tennis', '0007_rename_type_match_format_match_court_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='format',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('mix_double', 'Mix Double')], default='single', max_length=64),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='expiry_at',
            field=models.DateTimeField(default=tennis.models.MatchRequest.in_seven_days),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='format',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('mix_double', 'Mix Double')], default='single', max_length=64),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
