# Generated by Django 3.2.11 on 2022-03-13 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tennis', '0008_auto_20220310_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leagueapplication',
            name='players',
        ),
        migrations.AddField(
            model_name='leagueapplication',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL, to_field='user_id'),
        ),
    ]
