# Generated by Django 4.0.1 on 2022-01-20 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tennis', '0008_alter_match_format_alter_matchrequest_expiry_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player_four',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_player_four', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_player_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_player_three', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_player_two', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='accepted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
