# Generated by Django 3.2.11 on 2022-03-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0010_court'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('draw', 'Draw'), ('cancelled', 'Cancelled'), ('retire', 'Retire')], db_index=True, default='single', max_length=256),
        ),
    ]
