# Generated by Django 3.2.11 on 2022-04-18 00:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tennis', '0012_userquery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserQuery',
            new_name='UserEnquiry',
        ),
    ]
